name: Backend Despacho CI/CD

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: |
          chmod +x mvnw
          ./mvnw -B test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Despacho
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-despacho:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/backend-despacho:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/backend-despacho:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-despacho:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-despacho:latest

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

      - name: Deploy Backend Despacho en EC2
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/backend-despacho:latest
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/ec2-key.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          docker pull ${DOCKER_IMAGE}

          docker stop backend-despacho || true
          docker rm backend-despacho || true

          docker run -d \
            --name backend-despacho \
            -p 8081:8081 \
            --restart always \
            -e DB_ENDPOINT="${{ secrets.DB_ENDPOINT }}" \
            -e DB_PORT="3306" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            ${DOCKER_IMAGE}

          sleep 20

          curl -fsS http://localhost:8081/actuator/health || exit 1

          docker ps
          EOF
